# Generated by Django 4.1.1 on 2022-09-24 13:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_height_category_width_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='height',
        ),
        migrations.RemoveField(
            model_name='category',
            name='width',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='', validators=[main.models.validate_image]),
        ),
    ]
