# Generated by Django 4.1.1 on 2022-09-26 01:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_category_height_remove_category_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', validators=[main.models.validate_image]),
        ),
    ]
